/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package issuetracker;

/**
 *
 * @author Md Khakan
 */
public class Item extends javax.swing.JPanel {

    /**
     * Creates new form Item
     */
    public Item(String update, String issue, String time) {
        initComponents();
        lbUpdate.setText(update);
        lbIssue.setText(issue);
        lbTime.setText(time);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUpdate = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        lbIssue = new javax.swing.JLabel();

        setAutoscrolls(true);
        setOpaque(false);

        lbUpdate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbUpdate.setText("update");

        lbTime.setForeground(new java.awt.Color(153, 153, 153));
        lbTime.setText("1 day ago");

        lbIssue.setForeground(new java.awt.Color(153, 153, 153));
        lbIssue.setText("The issue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTime)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbIssue)
                        .addComponent(lbUpdate)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbIssue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTime)
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbIssue;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lbUpdate;
    // End of variables declaration//GEN-END:variables
}
